/** Semantic theme tokens consumed by blocks via Tailwind v4 classes like
 * `bg-brand-accent`, `text-brand-ink`, `font-brand-heading`. The CSS variable
 * values are injected per-site by the renderer; see `renderThemeStyle()` in
 * `apps/studio/src/lib/platform/theme.ts`. */

export type ColorToken =
  | "bg"
  | "surface"
  | "surface-dark"
  | "ink"
  | "ink-muted"
  | "ink-subtle"
  | "ink-inverse"
  | "border"
  | "accent"
  | "accent-hover"
  | "accent-fg"
  | "accent-soft"
  | "accent-2";

export type FontPair =
  | "geist"
  | "inter"
  | "manrope"
  | "fraunces"
  | "jetbrains"
  | "space-grotesk"
  | "playfair";

export type RadiusScale = "sm" | "md" | "lg";

export const RADIUS_VALUES: Record<RadiusScale, { card: string; pill: string }> = {
  sm: { card: "0.5rem", pill: "9999px" },
  md: { card: "1rem", pill: "9999px" },
  lg: { card: "1.5rem", pill: "9999px" },
};

/** Extended radius scale used by the new archetype presets. Bridges legacy
 * `RadiusScale` (sm/md/lg) with finer-grained options for brutalism (0) and
 * extra-rounded organic/playful looks. */
export type RadiusScaleX =
  | "none"
  | "xs"
  | "sm"
  | "md"
  | "lg"
  | "xl"
  | "2xl";

export const RADIUS_X_VALUES: Record<RadiusScaleX, { card: string; pill: string }> = {
  none: { card: "0", pill: "0" },
  xs: { card: "0.25rem", pill: "9999px" },
  sm: { card: "0.5rem", pill: "9999px" },
  md: { card: "1rem", pill: "9999px" },
  lg: { card: "1.5rem", pill: "9999px" },
  xl: { card: "2rem", pill: "9999px" },
  "2xl": { card: "3rem", pill: "9999px" },
};

/** CSS variables the renderer writes to `:root` per site.
 * Block classes are generated by Tailwind v4 from the `@color-brand-*`
 * entries in `globals.css`, which read these custom properties. */
export const CSS_VAR_NAMES: Record<ColorToken, string> = {
  "bg": "--brand-bg",
  "surface": "--brand-surface",
  "surface-dark": "--brand-surface-dark",
  "ink": "--brand-ink",
  "ink-muted": "--brand-ink-muted",
  "ink-subtle": "--brand-ink-subtle",
  "ink-inverse": "--brand-ink-inverse",
  "border": "--brand-border",
  "accent": "--brand-accent",
  "accent-hover": "--brand-accent-hover",
  "accent-fg": "--brand-accent-fg",
  "accent-soft": "--brand-accent-soft",
  "accent-2": "--brand-accent-2",
};

/** Maps a font-pair id to the CSS variables that `next/font/google` produces
 * in the studio root layout. Keep in sync with `apps/studio/src/app/layout.tsx`. */
export const FONT_PAIR_VARS: Record<FontPair, { heading: string; body: string }> = {
  geist: { heading: "var(--font-geist-sans)", body: "var(--font-geist-sans)" },
  inter: { heading: "var(--font-inter)", body: "var(--font-inter)" },
  manrope: { heading: "var(--font-manrope)", body: "var(--font-manrope)" },
  fraunces: { heading: "var(--font-fraunces)", body: "var(--font-inter)" },
  jetbrains: { heading: "var(--font-jetbrains)", body: "var(--font-inter)" },
  "space-grotesk": { heading: "var(--font-space-grotesk)", body: "var(--font-inter)" },
  playfair: { heading: "var(--font-playfair)", body: "var(--font-inter)" },
};

// ─── Round 2: style tokens ────────────────────────────────────────────
// These give each preset a distinct visual identity beyond colors/fonts.
// Hero-specific decorations (layout, accent-bar, gradient-title) live on
// the Hero block props, not here — themes control GLOBAL look only.

export type DividerKind =
  | "none"
  | "wave"
  | "tilt"
  | "dotted"
  | "solid"
  | "zigzag"
  | "double-line";

export type BgPattern =
  | "none"
  | "blob"
  | "noise"
  | "rays"
  | "dot-grid"
  | "grid"
  | "diagonal"
  | "halftone"
  | "scribble";

export type CardStyle =
  | "soft"
  | "soft-lg"
  | "outline"
  | "hard-offset"
  | "brutal"
  | "glass"
  | "sticker";

export type ButtonShape = "pill" | "rounded" | "sharp";
export type HeadingTransform = "none" | "uppercase";
export type HeadingTracking = "tightest" | "tighter" | "tight" | "normal";

/** Vertical-rhythm multiplier applied via `--brand-spacing-multiplier`. */
export type SpacingDensity = "tight" | "normal" | "comfortable" | "airy";

export const SPACING_MULTIPLIER: Record<SpacingDensity, string> = {
  tight: "0.75",
  normal: "1",
  comfortable: "1.15",
  airy: "1.35",
};

export type PresetStyle = {
  divider: DividerKind;
  bgPattern: BgPattern;
  cardStyle: CardStyle;
  buttonShape: ButtonShape;
  headingWeight: 400 | 500 | 600 | 700 | 800 | 900;
  headingTracking: HeadingTracking;
  headingTransform: HeadingTransform;
  /** New: vertical-rhythm density multiplier. */
  spacing: SpacingDensity;
  /** New: finer-grained radius scale; overrides `radius`/`cardStyle` defaults. */
  radiusX: RadiusScaleX;
};

export const TRACKING_VALUES: Record<HeadingTracking, string> = {
  tightest: "-0.06em",
  tighter: "-0.04em",
  tight: "-0.025em",
  normal: "0",
};

export const CARD_RADIUS_VALUES: Record<CardStyle, string> = {
  soft: "1rem",
  "soft-lg": "1.5rem",
  outline: "0.5rem",
  "hard-offset": "1rem",
  brutal: "0",
  glass: "1.25rem",
  sticker: "1rem",
};

export const BUTTON_RADIUS_VALUES: Record<ButtonShape, string> = {
  pill: "9999px",
  rounded: "0.5rem",
  sharp: "0",
};
