#!/usr/bin/env node
/**
 * Build-time generator: writes apps/tenant/public/_worker.js with an
 * inlined host → slug map. Pages serves _worker.js as an "advanced mode"
 * Worker that fronts every request, so it can rewrite tenant subdomains
 * and custom domains into /<slug>/... paths against the static export.
 */
import { readFileSync, readdirSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const SITES_DIR = path.resolve(process.cwd(), "..", "..", "sites");
const OUT = path.resolve(process.cwd(), "public", "_worker.js");

function readJson(p) {
  try {
    return JSON.parse(readFileSync(p, "utf-8"));
  } catch {
    return null;
  }
}

function collectDomainMap() {
  if (!existsSync(SITES_DIR)) return {};
  const map = {};
  for (const slug of readdirSync(SITES_DIR).sort()) {
    if (slug.startsWith(".")) continue;
    const cfg = readJson(path.join(SITES_DIR, slug, "config.json"));
    if (!cfg) continue;
    for (const d of cfg.domains ?? []) {
      map[String(d).toLowerCase()] = slug;
    }
  }
  return map;
}

const map = collectDomainMap();
const mapJson = JSON.stringify(map, null, 2);

const source = `// Generated by scripts/build-worker.mjs — do not edit by hand.
// Pages advanced-mode Worker. Rewrites tenant subdomain/custom-domain
// requests onto the static export's /<slug>/... layout, then forwards
// to the asset binding.

const HOST_TO_SLUG = ${mapJson};

// Asset paths Next.js emits at the root of the output — must not be
// rewritten under /<slug>/ or env.ASSETS.fetch returns 404.
const ASSET_PREFIXES = ["/_next/", "/favicon", "/icons/"];
const ASSET_EXT = /\\.(js|css|ico|png|jpe?g|gif|svg|webp|avif|woff2?|ttf|otf|map|json|txt|xml)$/i;

function isAsset(pathname) {
  if (ASSET_PREFIXES.some((p) => pathname.startsWith(p))) return true;
  if (ASSET_EXT.test(pathname)) return true;
  return false;
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const host = url.host.toLowerCase();
    const slug = HOST_TO_SLUG[host];

    if (slug && !isAsset(url.pathname)) {
      const prefix = "/" + slug;
      if (!url.pathname.startsWith(prefix + "/") && url.pathname !== prefix) {
        url.pathname = prefix + (url.pathname === "/" ? "/" : url.pathname);
        return env.ASSETS.fetch(new Request(url, request));
      }
    }

    return env.ASSETS.fetch(request);
  },
};
`;

mkdirSync(path.dirname(OUT), { recursive: true });
writeFileSync(OUT, source, "utf-8");
console.log(`worker: wrote ${OUT}`);
console.log(`worker: mapped ${Object.keys(map).length} hosts`);
for (const [host, slug] of Object.entries(map)) {
  console.log(`        ${host} → ${slug}`);
}
